project_id = "krhddximfgpnlciakfga"

[functions.motv-proxy]
verify_jwt = false

[functions.plans-resolve-package-code]
verify_jwt = false

[functions.auth-register]
verify_jwt = false

[functions.auth-delete-user]
verify_jwt = false

[functions.auth-check-user]
verify_jwt = false

[functions.manage-subscription-motv]
verify_jwt = false

[functions.asaas-create-customer]
verify_jwt = true

[functions.asaas-create-payment]
verify_jwt = true

[functions.asaas-webhook-handler]
verify_jwt = false

[functions.asaas-check-payment-status]
verify_jwt = true
